#! /bin/sh
#kill apps
killall lxsession
killall sxhkd
killall picom
killall flameshot

# start again apps
sxhkd &
lxsession &
picom --config ~/.config/picom/picom.conf &
easyeffects --gapplication-service &
flameshot &
$HOME/.config/polybar/launch.sh example &
xsetroot -cursor_name left_ptr &
nitrogen --restore &
xinput --set-prop '12' 'libinput Accel Speed' -0.6 &
pgrep -x sxhkd > /dev/null || sxhkd &

# keyboard layout
setxkbmap -option grp:alt_shift_toggle us,lt &

#workspaces
#bspc monitor DP-0 -d I 󰊠
#bspc monitor DP-2 -d I II III IV V
bspc monitor DP-0 -d 󰊠
bspc monitor DP-2 -d 󰊠 󰊠 󰊠 󰊠 󰊠


bspc config border_width         2
bspc config window_gap          12
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config top_padding 	0
bspc config focus_follows_pointer true
bspc config focused_border_color '#e0af68'
bspc config normal_border_color '#1a1b26' 
bspc config active_border_color '#1a1b26'
bspc config pointer_motion_interval 7ms
bspc config single_monocle true


# floating windows
bspc rule -a Thunar state=floating
bspc rule -a Pavucontrol state=floating
